force-app/main/default/objects/Finance_Information__c/Finance_Information__c.object-meta.xml
<CustomObject>
    <label>Cenveo Finance Information</label>
    <nameField>
        <displayFormat>FA {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Finance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cenveo Finance Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cenveo Finance Information</relationshipLabel>
    <relationshipName>Finance_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Information__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Information__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CL - Acclaim</fullName>
            </value>
            <value>
                <fullName>CL - Express Label</fullName>
            </value>
            <value>
                <fullName>CL - Lightning</fullName>
            </value>
            <value>
                <fullName>CL - Maverick</fullName>
            </value>
            <value>
                <fullName>CL - New Albany</fullName>
            </value>
            <value>
                <fullName>CL - Omaha</fullName>
            </value>
            <value>
                <fullName>CP - Lancaster</fullName>
            </value>
            <value>
                <fullName>CP - Toledo</fullName>
            </value>
            <value>
                <fullName>Envelope plants - Finance Only</fullName>
            </value>
            <value>
                <fullName>JDE - Master</fullName>
            </value>
            <value>
                <fullName>L&amp;P - Gilbreth</fullName>
            </value>
            <value>
                <fullName>L&amp;P - International</fullName>
            </value>
            <value>
                <fullName>MMT</fullName>
            </value>
            <value>
                <fullName>Nashua</fullName>
            </value>
            <value>
                <fullName>NEC - Finance Only</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>CP - Amarillo</fullName>
            </value>
            <value>
                <fullName>CP - Clixx</fullName>
            </value>
            <value>
                <fullName>CP - Conklin</fullName>
            </value>
            <value>
                <fullName>CP - Content</fullName>
            </value>
            <value>
                <fullName>CP - Easton</fullName>
            </value>
            <value>
                <fullName>CP - Garland</fullName>
            </value>
            <value>
                <fullName>CP - Hurlock</fullName>
            </value>
            <value>
                <fullName>CP - Los Angeles</fullName>
            </value>
            <value>
                <fullName>CP - Minneapolis East</fullName>
            </value>
            <value>
                <fullName>CP - Port City</fullName>
            </value>
            <value>
                <fullName>CP - Portland</fullName>
            </value>
            <value>
                <fullName>CP - Richmond</fullName>
            </value>
            <value>
                <fullName>CP - San Antonio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/Name_Mapping_Configuration__c.object-meta.xml
<CustomObject>
    <label>Name Mapping Configuration</label>
    <nameField>
        <displayFormat>NMC-{00000000}</displayFormat>
        <label>Name Mapping Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Mapping Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Name Mapping Configurations</relationshipLabel>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Billing_System__c.field-meta.xml
<CustomField>
    <fullName>Billing_System__c</fullName>
    <label>Business Units</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Envelop</fullName>
            </value>
            <value>
                <fullName>Commercial Printing</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Merrimack</fullName>
            </value>
            <value>
                <fullName>Acclaim</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Mapped_Value__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Value__c</fullName>
    <label>Mapped Value</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Name Mapping Configurations</relationshipLabel>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/SFDC_Value__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Value__c</fullName>
    <label>SFDC Value</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Name</fullName>
            </value>
            <value>
                <fullName>Billing Account Number</fullName>
            </value>
            <value>
                <fullName>Plant Product Name</fullName>
            </value>
            <value>
                <fullName>User Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Products__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/Raw_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Raw Sales Data</label>
    <nameField>
        <displayFormat>RS- {00000000}</displayFormat>
        <label>Raw Sales Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raw Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Billing_System__c.field-meta.xml
<CustomField>
    <fullName>Billing_System__c</fullName>
    <label>Business Unit Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acclaim</fullName>
            </value>
            <value>
                <fullName>Commercial Print</fullName>
            </value>
            <value>
                <fullName>DLI</fullName>
            </value>
            <value>
                <fullName>Envelope</fullName>
            </value>
            <value>
                <fullName>Express Labels</fullName>
            </value>
            <value>
                <fullName>Labels &amp; Packaging</fullName>
            </value>
            <value>
                <fullName>Lancer</fullName>
            </value>
            <value>
                <fullName>Lightning Labels</fullName>
            </value>
            <value>
                <fullName>Maverick Label</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Sales_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Data</label>
    <referenceTo>Sales_Data__c</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <label>Billing Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <formula>Plant_Product__r.Plant__r.Name</formula>
    <label>Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data_Upload_Configurations__c/Sales_Data_Upload_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Sales Data Upload Configurations</label>
</CustomObject>

force-app/main/default/objects/Sales_Data_Upload_Configurations__c/fields/Process_Records_Limit__c.field-meta.xml
<CustomField>
    <fullName>Process_Records_Limit__c</fullName>
    <label>Process Records Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data_Upload_Configurations__c/fields/Successfully_Records_Limit__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Records_Limit__c</fullName>
    <label>Successfully Records Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data_Upload_Configurations__c/fields/With_Error_Records_Limit__c.field-meta.xml
<CustomField>
    <fullName>With_Error_Records_Limit__c</fullName>
    <label>With Error Records Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data_Upload_Configurations__c/fields/Without_Error_Records_Limit__c.field-meta.xml
<CustomField>
    <fullName>Without_Error_Records_Limit__c</fullName>
    <label>Without Error Records Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SalesDataUploadSummaryControllerTest.cls
@isTest(SeeAllData=false)
public class SalesDataUploadSummaryControllerTest{

    static testMethod void unitTest01(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId, PeopleSoft_Acct__c = '9874563210'));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210',PeopleSoft_Acct__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'acclaim', Type__c = 'Billing Account Number', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Acclaim';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    static testMethod void unitTest03(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Billing Account Number', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Acclaim';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    
     static testMethod void unitTest02(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4',Type= 'Customer', Billing_Account_Number__c = '9874563210',PeopleSoft_Acct__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true,Error_In_Processing__c= true
                                                ));
                                                
           /* listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));*/
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Acclaim';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    
    static testMethod void unitTest04(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Labels & Packaging', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true,Error_In_Processing__c= true
                                                ));
                                                
           /* listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));*/
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Labels & Packaging';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    
    static testMethod void unitTest05(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId,PeopleSoft_Acct__c = '9874563210'));
            listAccount.add(new Account(Name = 'Test Account4',Type= 'Customer', Billing_Account_Number__c = '9874563210',PeopleSoft_Acct__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true,Error_In_Processing__c= true
                                                ));
                                                
           /* listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));*/
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Acclaim';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    
    static testMethod void unitTest06(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        
        System.RunAs(u) {
            Sales_Data_Upload_Configurations__c sduc = new Sales_Data_Upload_Configurations__c(Process_Records_Limit__c = 1, Without_Error_Records_Limit__c = 1, Successfully_Records_Limit__c = 1, With_Error_Records_Limit__c = 1);
            insert sduc;
			Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210',PeopleSoft_Acct__c = '9874563210', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            Finance_Information__c fi = new Finance_Information__c (Account_Number__c = '0987456321', Account__c = listAccount.get(2).id);
            insert fi;
            
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            insert listNMC;
            
            //System.assert(false, listNMC);
            
            listSD.add(new Sales_Data__c(Period__c = Decimal.valueOf(datetime.now().addMonths(-1).month())));
            insert listSD;
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.ValueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true,Error_In_Processing__c= true
                                                ));
                                                
           /* listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account4', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '9874563210', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));
            
            listRSD.add(new Raw_Sales_Data__c(Billing_Account_Number__c = '0987456321', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = false
                                                ));                                    
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = null
                                                ));
                                                
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = 'Error Message'
                                                ));                                                                        
            
            listRSD.add(new Raw_Sales_Data__c(Account_Name__c = 'Test Account', Rep_Name__c = 'Testing User', Plant_Name__c = 'Test Plant name-',
                                                Billing_System__c = 'Acclaim', Year__c = '2015', Period__c = String.valueOf(datetime.now().addMonths(-1).month()),
                                                Actual__c = 500, Actual_Unit__c = '2', GMDollars__c = 200, Processed__c = true, Error_Log__c  = '',
                                                Sales_Data__c = listSD.get(0).Id
                                                ));*/
            insert listRSD;
        }
        
        test.startTest();
        	
        	List<Raw_Sales_Data__c> rowSales = [Select Id,Year__c,Period__c from Raw_Sales_Data__c];
        	system.debug('$$$$$$$$$$'+ rowSales.size());
        	system.debug('$$$$$$$$$$'+ rowSales[0].Year__c);
        	system.debug('$$$$$$$$$$'+ rowSales[0].Period__c);
        	
            SalesDataUploadSummaryController controller = new SalesDataUploadSummaryController();
            controller.rawSalesData = listRSD.get(0);
            controller.selectedMonth = datetime.now().addMonths(-1).format('MMM').trim();
            controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.selectedBusinessUnit = 'Acclaim';
            controller.process();
            //controller.businesUnits.add(new SelectOption('Acclaim', 'Acclaim'));
            controller.moveToSalesData();
            controller.nmc = createNMC();
            controller.saveMapping();
            
            controller.nextProcess();
            controller.previousProcess();
            
            controller.nextWithoutError();
            controller.previousWithoutError();
            
            controller.next();
            controller.previous();
            
            controller.nextWithError();
            controller.previousWithError();
        test.stopTest();
    }
    public static User createUser() {
        Profile p = [select id from profile where name = 'System Administrator'];
        User u = new User(alias = 'tesusr', email = 'testinguser@newtest.com',
            emailencodingkey = 'UTF-8', lastname = 'Testing User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = p.Id,
            timezonesidkey = 'America/Los_Angeles', username = 'testinguser@newtest.com',EmployeeNumber = '34334');
        return u;
    }
    
    
    public static Name_Mapping_Configuration__c createNMC(){
        Name_Mapping_Configuration__c nmc = new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account name', Mapped_Value__c = 'Test Account' );
        return nmc;
    }

}