force-app/main/default/objects/T_E__c/T_E__c.object-meta.xml
<CustomObject>
    <description>Travel and Expense module for Sales and Marketing</description>
    <label>T&amp;E</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>T&amp;E</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;E</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/T_E__c/fields/Account_1__c.field-meta.xml
<CustomField>
    <fullName>Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account #1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>T&amp;E</relationshipLabel>
    <relationshipName>T_E</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_1_OPEN_ACTIVITIES_TEXT__c.field-meta.xml
<CustomField>
    <fullName>Account_1_OPEN_ACTIVITIES_TEXT__c</fullName>
    <label>Account #1 OPEN ACTIVITIES</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_2__c.field-meta.xml
<CustomField>
    <fullName>Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account #2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>T&amp;E (Account #2)</relationshipLabel>
    <relationshipName>T_E2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_2_OPEN_ACTIVITIES_TEXT__c.field-meta.xml
<CustomField>
    <fullName>Account_2_OPEN_ACTIVITIES_TEXT__c</fullName>
    <label>Account #2 OPEN ACTIVITIES</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_3__c.field-meta.xml
<CustomField>
    <fullName>Account_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account #3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>T&amp;E (Account #3)</relationshipLabel>
    <relationshipName>T_E1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_4__c.field-meta.xml
<CustomField>
    <fullName>Account_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account #4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>T&amp;E (Account #4)</relationshipLabel>
    <relationshipName>T_E3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/T_E__c/fields/Account_4_OPEN_ACTIVITIES_TEXT__c.field-meta.xml
<CustomField>
    <fullName>Account_4_OPEN_ACTIVITIES_TEXT__c</fullName>
    <label>Account #4 OPEN ACTIVITIES</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TETriggerHelper.cls
/**
 *	Purpose			:	This class is helper class for trigger on User object.
 *               
 *  Create By		:	
 *   
 *  Created Date	:	
 *   
 *   Revision Log	:	
 *
 **/
public without sharing class TETriggerHelper {
		
	/**
	 *	@description	:	This method is to pull the Open Activities from Account to T&E
	 *
	 *	@args			:	List of New TEs
	 *
	 *	@return			:	void
	 *
	 **/
	public static void populateTEData(List<T_E__c> listTEs) {
		
		//Create a set to hold the set of account Ids
		Set<Id> accIds = new Set<Id>();
		
		//Loop through the TEs and populate the Account Ids set
		for(T_E__c tE : listTEs) {
			
			//Check for the Null
			if(tE.Account_1__c != null)
				accIds.add(tE.Account_1__c);
			if(tE.Account_2__c != null)
				accIds.add(tE.Account_2__c);
			if(tE.Account_3__c != null)
				accIds.add(tE.Account_3__c);
			if(tE.Account_4__c != null)
				accIds.add(tE.Account_4__c);
		}
		
		//Check for the size
		if(accIds.size() == 0)
			return;
		
		//Pull accounts from data base
		Map<Id, Account> mapAccounts = new Map<Id, Account>([Select Id, OPEN_ACTIVITIES__c from Account where Id IN: accIds]); 
		
		//Loop through the TEs and populate the Account Ids set
		for(T_E__c tE : listTEs) {
			
			//Check for the Null
			if(tE.Account_1__c != null && mapAccounts.containsKey(tE.Account_1__c))
				tE.Account_1_OPEN_ACTIVITIES_TEXT__c = mapAccounts.get(tE.Account_1__c).OPEN_ACTIVITIES__c;
			if(tE.Account_2__c != null && mapAccounts.containsKey(tE.Account_2__c))
				tE.Account_2_OPEN_ACTIVITIES_TEXT__c = mapAccounts.get(tE.Account_2__c).OPEN_ACTIVITIES__c;
			if(tE.Account_3__c != null && mapAccounts.containsKey(tE.Account_3__c))
				tE.Account_4_OPEN_ACTIVITIES_TEXT__c = mapAccounts.get(tE.Account_3__c).OPEN_ACTIVITIES__c;
			if(tE.Account_4__c != null && mapAccounts.containsKey(tE.Account_4__c))
				tE.Account_4_OPEN_ACTIVITIES_TEXT__c = mapAccounts.get(tE.Account_4__c).OPEN_ACTIVITIES__c;
		}
	}
}