force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvokeUpdatePeriodEndDate.cls
public with sharing class InvokeUpdatePeriodEndDate {
	public PageReference invoke(){
		String strQuery = 'SELECT Id, Year__c, Period__c, Period_End_Date__c FROM Sales_Data__c where Period_End_Date__c = null';
		
		if(Test.isRunningTest()){
			strQuery = 'SELECT Id, Year__c, Period__c, Period_End_Date__c FROM Sales_Data__c where Period_End_Date__c = null LIMIT 1';
		}
		
		UpdatePeriodEndDateBatch rr = new UpdatePeriodEndDateBatch();
   		rr.strQuery = strQuery;
    	id batchstart= Database.executeBatch(rr);
    	return null;
	}
}