force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateAccountTypeOnSales.cls
global with sharing class Batch_UpdateAccountTypeOnSales implements Database.Batchable<sobject>, Database.Stateful {
	
	/**
	 *	@ Description		:		Start method of Batch
	 *
	 *	@ Args				:		Database.BatchableContext bc
	 *
 	 *	@ Return 			:		Database.QueryLocator
 	 **/
    global Database.QueryLocator start(Database.BatchableContext bc){
		
		//Query string
		String queryString = 'Select Id,Actual_Amount__c, Account__r.Type from Sales_Data__c where (Account__r.RecordType.DeveloperName = \'Cenveo\' AND Account__r.Type != \'Customer\' AND Actual_Amount__c != null AND Actual_Amount__c > 0)';
		
		//Execute uery and return to execute
		return Database.getQueryLocator(queryString);
    }
	
	/**
	 *	@ Description		:		Execute method of Batch
	 *
	 *	@ Args				:		Database.batchableContext bc, List<Sales_Data__c> listSalesData
	 *
 	 *	@ Return 			:		Void
 	 **/
    global void execute(Database.batchableContext bc, List<Sales_Data__c> listSalesData ) {
    	
    	//Set of Account ids
		Set<Id> setAccountIds = new Set<Id>();
		
		//Check for size of list of sales data
		if(listSalesData.size() > 0) {
			
			//Loop through Sales data list
			for(Sales_Data__c sd : listSalesData) {
				
				//Check sales data Account Type Customer or prospect does not
				if(sd.Account__r.Type != 'Customer') {
					
					//Add Id of account into set of Ids
					setAccountIds.add(sd.Account__c);
				}
			}
		}
		
		system.debug('setAccountIds'+setAccountIds);
		//Query List of Account
		List<Account> accountList = [Select Id, Type from Account where Id IN : setAccountIds];
	 	
	 	//check for  size of list
	 	if(accountList.size() > 0) {
	 		
	 		//Loop through list of account
	 		for(Account acc : accountList) {
	 			
	 			//change Type of Account into Customer
	 			acc.Type = 'Customer';
	 		}
 		
 		//DML operation
		update accountList;
		}
    }
	
	/**
	 *	@ Description		:		Finish method of Batch
	 *
	 *	@ Args				:		Database.batchableContext bc, List<Sales_Data__c> listSalesData
	 *
 	 *	@ Return 			:		Void
 	 **/
    global void finish(Database.batchableContext bc){

    }

}