force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Forecast_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Amount__c</fullName>
    <description>Update the forecast dollar ($) amount.</description>
    <inlineHelpText>Update the forecast dollar ($) amount.</inlineHelpText>
    <label>Forecast Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/GM__c.field-meta.xml
<CustomField>
    <fullName>GM__c</fullName>
    <description>Gross Margin %</description>
    <inlineHelpText>Gross Margin %</inlineHelpText>
    <label>GM %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/GMDollars__c.field-meta.xml
<CustomField>
    <fullName>GMDollars__c</fullName>
    <label>GM $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Margin_Sales_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Margin_Sales_Dollars__c</fullName>
    <label>Margin Sales Dollars</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchAccountSalesDataRollup.cls
/*
    Apex class to calcualte account sales data rollups
*/
global without sharing class BatchAccountSalesDataRollup implements Database.Batchable<sobject>, Database.Stateful {

    public String strQuery = 'Select Id From Account Where Type != \'Parent\' and Recordtype.DeveloperName = \'Cenveo\'  Order By CreatedDate DESC';
    public Set<Id> setAccountIds;
    
    public static Set<Id> accountIds;
    
    public static void runAccountSalesDataRollupForAccounts( Set<Id> setAccountIdVal ){

          String strQuery;
          BatchAccountSalesDataRollup clsAccountSalesDataRollup = new BatchAccountSalesDataRollup();
          clsAccountSalesDataRollup.setAccountIds = setAccountIdVal;
          clsAccountSalesDataRollup.strQuery =  ' Select Id From Account Where Type != \'Parent\' and Recordtype.DeveloperName = \'Cenveo\'  And Id in : setAccountIds '
                                              + ' Order By CreatedDate DESC ';

          id batchstart = Database.executeBatch(clsAccountSalesDataRollup,1);

    }

    global Database.QueryLocator start(Database.BatchableContext bc){

        return Database.getQueryLocator(strQuery);
    }

    global void execute(Database.batchableContext bc, List<Account> listAccount ) {

        List<Sales_Data__c> listSalesdata = [ SELECT Id, GM__c, GMDollars__c, Margin_Sales_Dollars__c, Account__c,
                                                     Budget_Amount__c, Year__c, Period__c,
                                                     Actual_Amount__c, Forecast_Amount__c
                                              FROM Sales_Data__c
                                              Where Account__c in: listAccount
                                              Order By Account__c
                                             ]; 
        accountIds = new Set<Id>();
        for( Account acc : listAccount ) {
            accountIds.add( acc.Id );   
        }

        /*AccountSalesDataRollup clsAccSalesRollup = new AccountSalesDataRollup(' Select Id Form Sales_Data__c ');
        AccountSalesDataRollup.executeCal = true;
        clsAccSalesRollup.calcualteAccountSalesDataRollup( listSalesdata );*/
        AccountSalesDataRollupAsFiscalYear clsAccSalesRollup = new AccountSalesDataRollupAsFiscalYear();
        //AccountSalesDataRollupClone.executeCal = true;
        clsAccSalesRollup.calcualteAccountSalesDataRollup(listSalesdata);

    }

    global void finish(Database.batchableContext bc){

        //AccountSalesDataRollup clsAccSalesRollup = new AccountSalesDataRollup(' Select Id Form Sales_Data__c ');
        AccountSalesDataRollupAsFiscalYear clsAccSalesRollup = new AccountSalesDataRollupAsFiscalYear();
        clsAccSalesRollup.finishActions(bc);

        RollupAccountBudgetAndSalesToParent r = new RollupAccountBudgetAndSalesToParent();
        Database.executeBatch(r, 10);
        
    }
}