force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Forecast_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Amount__c</fullName>
    <description>Update the forecast dollar ($) amount.</description>
    <inlineHelpText>Update the forecast dollar ($) amount.</inlineHelpText>
    <label>Forecast Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_AccountSalesDataRollupClone.cls
@isTest
private class Test_AccountSalesDataRollupClone {
	public static User managerUser1;
    @testSetup 
    public static void setupmethod(){
	 Profile p = [select id from profile where name='System Administrator'];
        
     String name = 'A-test1';
     managerUser1 = new User(Alias = name, Email = name + '@asdfg.junk', EmailEncodingKey = 'UTF-8',
            FirstName = 'Test', lastname = name, LanguageLocaleKey = 'en_US', LocaleSIDKey = 'en_US',
            Profileid = p.Id, TimezoneSIDKey = 'America/Los_Angeles', Username = name + '@asdfg.junk',EmployeeNumber = '101');
        
        insert managerUser1;        
    }
    static testMethod void myUnitTest() {
		User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
			//create Account
	        Account acc = new Account();
	        acc.Name='Test Acc';
	        acc.Industry = 'Business Services';
	        acc.Type = 'Customer';
        	acc.RecordTypeId = recordTypeId;
        	acc.OwnerId = managerUser.Id;
	        insert acc;

	        //create List of sales data
	        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
	        
	        Sales_Data__c sd = new Sales_Data__c();
	        sd.Year__c = '2013';
	        sd.Period__c = 2;
	        sd.Actual_Amount__c = 100;
	        sd.Account__c = acc.id;
	        sdlist.add(sd);
	        
	        Sales_Data__c sd1 = new Sales_Data__c();
	        sd1.Year__c = '2015';
	        sd1.Period__c = 2;
	        sd1.Actual_Amount__c = 100;
	        sd1.Account__c = acc.id;
	        sdlist.add(sd1);
			
			Sales_Data__c sd2 = new Sales_Data__c();
	        sd2.Year__c = '2017';
	        sd2.Period__c = 2;
	        sd2.Actual_Amount__c = 100;
	        sd2.Account__c = acc.id;
	        sdlist.add(sd2);
	        
	        //Insert Sales data records
			insert sdlist;
			
			//Test Start here
			Test.startTest();
			
		//	AccountSalesDataRollupClone.executeCal = true;
			
			//Call batch method
			AccountSalesDataRollupClone controller = new AccountSalesDataRollupClone();
			controller.calcualteAccountSalesDataRollup( sdlist );
			
			//Test stop here
			Test.stopTest();
			
			List<Account> accs = [Select Id,X2014_Sales__c,X2017_Sales__c,X2015_Sales__c,X2013_Sales__c,Previous_2Last_12Mo_Sales__c from Account where Name = 'Test Acc'];
			
			//Assert
			
    }
    
    //Test method
    
    static testMethod void myUnitTest1() {
		User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
			//create Account
	        Account acc = new Account();
	        acc.Name='Test Acc';
	        acc.Industry = 'Business Services';
	        acc.Type = 'Customer';
        	acc.RecordTypeId = recordTypeId;
        	acc.OwnerId = managerUser.Id;
	        insert acc;

	        //create List of sales data
	        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
	        
	        Sales_Data__c sd = new Sales_Data__c();
	        sd.Actual_Amount__c = 100;
	        sd.Account__c = acc.id;
	        sdlist.add(sd);
	        
	        Sales_Data__c sd1 = new Sales_Data__c();
	        sd1.Year__c = '2015';
	        sd1.Period__c = 3;
	        sd1.Actual_Amount__c = 100;
	        sd1.Account__c = acc.id;
	        sdlist.add(sd1);
	        
	         Sales_Data__c sd2 = new Sales_Data__c();
	        sd2.Year__c = '2015';
	        sd2.Period__c = 4;
	        sd2.Actual_Amount__c = 100;
	        sd2.Account__c = acc.id;
	        sdlist.add(sd2);
			
			Sales_Data__c sd3 = new Sales_Data__c();
	        sd3.Year__c = '2014';
	        sd3.Period__c = 10;
	        sd3.Actual_Amount__c = 100;
	        sd3.Account__c = acc.id;
	        sdlist.add(sd3);
	        
	        Sales_Data__c sd4 = new Sales_Data__c();
	        sd4.Year__c = '2014';
	        sd4.Period__c = 9;
	        sd4.Actual_Amount__c = 100;
	        sd4.Account__c = acc.id;
	        sdlist.add(sd4);
	        
	        //Insert Sales data records
			insert sdlist;
			
			//Test Start here
			Test.startTest();
			
			//AccountSalesDataRollupClone.executeCal = true;
			
			//Call batch method
			AccountSalesDataRollupClone controller = new AccountSalesDataRollupClone();
			controller.calcualteAccountSalesDataRollup( sdlist );
			
			//Test stop here
			Test.stopTest();
			
			List<Account> accs = [Select Id,X2014_Sales__c,X2017_Sales__c,X2015_Sales__c,X2013_Sales__c,Previous_2Last_12Mo_Sales__c from Account where Name = 'Test Acc'];
			
			//Assert
    }
    
    //Test method
    
    static testMethod void myUnitTest2() {
			User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
			//create Account
	        Account acc = new Account();
	        acc.Name='Test Acc';
	        acc.Industry = 'Business Services';
	        acc.Type = 'Customer';
        	acc.RecordTypeId = recordTypeId;
        	acc.OwnerId = managerUser.Id;
	        insert acc;

	        //create List of sales data
	        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
	        
	        Sales_Data__c sd = new Sales_Data__c();
	        sd.Actual_Amount__c = 100;
	        sd.Account__c = acc.id;
	        sdlist.add(sd);
	        
	        Sales_Data__c sd1 = new Sales_Data__c();
	        sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 12 ? 12 : date.today().month()+1;
	        sd1.Actual_Amount__c = 100;
	        sd1.Account__c = acc.id;
	        sd1.Forecast_Amount__c = 1000;
	        sdlist.add(sd1);
	        
	         Sales_Data__c sd2 = new Sales_Data__c();
	        sd2.Year__c = String.valueOf(Date.Today().Year()-1);
	        sd2.Period__c = date.today().month() == 1 ? 1 : date.today().month()-1;
	        sd2.Actual_Amount__c = 100;
	        sd2.Account__c = acc.id;
	        sdlist.add(sd2);
			
			Sales_Data__c sd3 = new Sales_Data__c();
	        sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 12 ? 12 : date.today().month()+1;
	        sd3.Actual_Amount__c = 100;
	        sd3.Account__c = acc.id;
	        sdlist.add(sd3);
	        
	        Sales_Data__c sd4 = new Sales_Data__c();
	       	sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 12 ? 12 : date.today().month()-1;
	        sd4.Actual_Amount__c = 100;
	        sd4.Account__c = acc.id;
	        sd4.Forecast_Amount__c = 1000;
	        sdlist.add(sd4);
	        
	        //Insert Sales data records
			insert sdlist;
			
			//Test Start here
			Test.startTest();
			
			//AccountSalesDataRollupClone.executeCal = false;
			acc.Last_Modified_CurrYBudget__c = DateTime.now();
			update acc;
			
			
			//Call batch method
			AccountSalesDataRollupClone controller = new AccountSalesDataRollupClone();
			controller.calcualteAccountSalesDataRollup( sdlist );
			
			//Test stop here
			Test.stopTest();
			
			List<Account> accs = [Select Id,X2014_Sales__c,X2017_Sales__c,X2015_Sales__c,X2013_Sales__c,Previous_2Last_12Mo_Sales__c from Account where Name = 'Test Acc'];
			
			//Assert
			
    }
    //Test method
    
    static testMethod void myUnitTest3() {
		User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
			//create Account
	        Account acc = new Account();
	        acc.Name='Test Acc';
	        acc.Industry = 'Business Services';
	        acc.Type = 'Customer';
        acc.RecordTypeId = recordTypeId;
        	acc.OwnerId = managerUser.Id;
	        insert acc;
			
			Account acc1 = new Account();
	        acc1.Name='Test Acc1';
	        acc1.Industry = 'Business Services';
	        acc1.Type = 'Customer';
        acc1.RecordTypeId = recordTypeId;
        	acc1.OwnerId = managerUser.Id;
	        insert acc1;
			
			
	        //create List of sales data
	        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
	        
	        Sales_Data__c sd = new Sales_Data__c();
	        sd.Actual_Amount__c = 100;
	        sd.Account__c = acc.id;
	        sdlist.add(sd);
	        
	        Sales_Data__c sd1 = new Sales_Data__c();
	        sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 12 ? 12 : date.today().month()+1;
	        sd1.Actual_Amount__c = 100;
	        sd1.Account__c = acc.id;
	        sd1.Forecast_Amount__c = 1000;
	        sdlist.add(sd1);
	        
	         Sales_Data__c sd2 = new Sales_Data__c();
	        sd2.Year__c = String.valueOf(Date.Today().Year()-1);
	        sd2.Period__c = date.today().month() == 1 ? 1 : date.today().month()-1;
	        sd2.Actual_Amount__c = 100;
	        sd2.Account__c = acc.id;
	        sdlist.add(sd2);
			
			Sales_Data__c sd3 = new Sales_Data__c();
	        sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 12 ? 12 : date.today().month()+1;
	        sd3.Actual_Amount__c = 100;
	        sd3.Account__c = acc1.id;
	        sd3.Forecast_Amount__c =1000;
	        sd3.Budget_Amount__c =1000;
	        sdlist.add(sd3);
	        
	        Sales_Data__c sd4 = new Sales_Data__c();
	       	sd1.Year__c = String.valueOf(Date.Today().Year());
	        sd1.Period__c = date.today().month() == 1 ? 1 : date.today().month()-1;
	        sd4.Actual_Amount__c = 100;
	        sd4.Account__c = acc.id;
	        sd4.Forecast_Amount__c = 1000;
	        sdlist.add(sd4);
	        
	        sd4 = new Sales_Data__c();
	       	sd1.Year__c = String.valueOf(Date.Today().Year()-1);
	        sd1.Period__c = date.today().month() == 1 ? 1 : date.today().month()-1;
	        sd4.Actual_Amount__c = 100;
	        sd4.Account__c = acc.id;
	        sd4.Forecast_Amount__c = 1000;
	        sdlist.add(sd4);
	        
	        //Insert Sales data records
			insert sdlist;
			
			//Test Start here   
			Test.startTest();
			
			//AccountSalesDataRollupClone.executeCal = false;
			acc.Last_Modified_CurrYBudget__c = DateTime.now();
			update acc;
			
			acc.Id = null;
			//Call batch method
			AccountSalesDataRollupClone controller = new AccountSalesDataRollupClone();
			controller.calcualteAccountSalesDataRollup( sdlist );
			
			//Test stop here
			Test.stopTest();
			
			List<Account> accs = [Select Id,X2014_Sales__c,X2017_Sales__c,X2015_Sales__c,X2013_Sales__c,Previous_2Last_12Mo_Sales__c from Account where Name = 'Test Acc'];
			
			
    }
}