force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Units__c.field-meta.xml
<CustomField>
    <fullName>Actual_Units__c</fullName>
    <label>Actual Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Batch_UpdateAccountTypeOnSales.cls
@isTest
private class Test_Batch_UpdateAccountTypeOnSales {
	public static User managerUser1;
    @testSetup 
    public static void setupmethod(){
	 Profile p = [select id from profile where name='System Administrator'];
        
     String name = 'A-test1';
     managerUser1 = new User(Alias = name, Email = name + '@asdfg.junk', EmailEncodingKey = 'UTF-8',
            FirstName = 'Test', lastname = name, LanguageLocaleKey = 'en_US', LocaleSIDKey = 'en_US',
            Profileid = p.Id, TimezoneSIDKey = 'America/Los_Angeles', Username = name + '@asdfg.junk',EmployeeNumber = '101');
        
        insert managerUser1;        
    }
    static testMethod void myUnitTest() {
    	User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
    	Test.startTest();
    	
    	//List of Accounts for customer
   		List<Account> accounts = new List<Account>();
       
        //Create Account and add to list
        for(Integer i = 0;i < 3; i++) {
          Account acc = new Account(Name='Test'+i+'Acc',Industry = 'Business Services',Type = 'Prospect',recordTypeId=recordTypeId);
          accounts.add(acc);
        }
        
        //insert list of  Account
        System.runAs(managerUser){
            insert accounts;
        }
        
        
        //List of sales data
        List<Sales_Data__c> sdList = new List<Sales_Data__c>();
        
        //Create Sales Data and add to list
        for(Integer i = 0; i < accounts.size(); i++) {
          
          Sales_Data__c sd = new Sales_Data__c();
          sd.Account__c = accounts[i].Id;
          sd.Year__c = String.valueOf(Date.today().Year());
          sd.Period__c = 10;
          sd.Actual_Amount__c = 100;   
          sd.Actual_Units__c = 20;
          sdList.add(sd);
        }
        
        //Insert Sales Data records
        insert sdList;
        
        //Query Account records which created
        List<Account> accs = [Select Id, Type from Account where Id IN:accounts];
        
        //Change Type on Accounts
       	accs[0].Type = 'Partner';
       	accs[1].Type = 'Prospect';
       	
       	//Update operation on Account
       	update accs;
       	
       	//Batch instantiate andd execute Batch
       	Batch_UpdateAccountTypeOnSales batch = new Batch_UpdateAccountTypeOnSales();
       	DataBase.executeBatch(batch);
        
        //Test stop
        Test.stopTest();
        
        //Query Account records
        accs = [Select Id,Type from Account where Id IN : accs];
        
        //Asserts
        system.assertEquals('Customer',accs[0].Type);
        system.assertEquals('Customer',accs[1].Type);
        system.assertEquals('Customer',accs[2].Type);
    }
}