force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_SalesDataBlankUpdate.cls
global with sharing class Batch_SalesDataBlankUpdate implements Database.Batchable<sobject> {
    
    //String used in query
    public String str = '';
    
    //To hold Query String
    public String strQuery = '';
    
    //Constructor
    global Batch_SalesDataBlankUpdate (String str1) {
        
        str = str1;
    }
    
    //Start method of Batch
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        //Set query in string
        strQuery = 'Select Id from Sales_Data__c where Month__c = null Order By ' + str +'';
         
        //return query 
        return Database.getQueryLocator(strQuery);
    }
    
    //Execute method of batch
    global void execute(Database.batchableContext bc, List<Sales_Data__c> lisSalesData ) {      
        
        //update salesData list
        update lisSalesData;
    }
    
    //finish method of batch
    global void finish(Database.batchableContext bc){
    
    }
}