force-app/main/default/objects/Name_Mapping_Configuration__c/Name_Mapping_Configuration__c.object-meta.xml
<CustomObject>
    <label>Name Mapping Configuration</label>
    <nameField>
        <displayFormat>NMC-{00000000}</displayFormat>
        <label>Name Mapping Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Mapping Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Name Mapping Configurations</relationshipLabel>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Billing_System__c.field-meta.xml
<CustomField>
    <fullName>Billing_System__c</fullName>
    <label>Business Units</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Envelop</fullName>
            </value>
            <value>
                <fullName>Commercial Printing</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Merrimack</fullName>
            </value>
            <value>
                <fullName>Acclaim</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Mapped_Value__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Value__c</fullName>
    <label>Mapped Value</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Name Mapping Configurations</relationshipLabel>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/SFDC_Value__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Value__c</fullName>
    <label>SFDC Value</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Name</fullName>
            </value>
            <value>
                <fullName>Billing Account Number</fullName>
            </value>
            <value>
                <fullName>Plant Product Name</fullName>
            </value>
            <value>
                <fullName>User Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_Mapping_Configuration__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Name_Mapping_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Products__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/Raw_Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Raw Sales Data</label>
    <nameField>
        <displayFormat>RS- {00000000}</displayFormat>
        <label>Raw Sales Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raw Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Billing_System__c.field-meta.xml
<CustomField>
    <fullName>Billing_System__c</fullName>
    <label>Business Unit Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acclaim</fullName>
            </value>
            <value>
                <fullName>Commercial Print</fullName>
            </value>
            <value>
                <fullName>DLI</fullName>
            </value>
            <value>
                <fullName>Envelope</fullName>
            </value>
            <value>
                <fullName>Express Labels</fullName>
            </value>
            <value>
                <fullName>Labels &amp; Packaging</fullName>
            </value>
            <value>
                <fullName>Lancer</fullName>
            </value>
            <value>
                <fullName>Lightning Labels</fullName>
            </value>
            <value>
                <fullName>Maverick Label</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raw_Sales_Data__c/fields/Sales_Data__c.field-meta.xml
<CustomField>
    <fullName>Sales_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Data</label>
    <referenceTo>Sales_Data__c</referenceTo>
    <relationshipLabel>Raw Sales Data</relationshipLabel>
    <relationshipName>Raw_Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Billing_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account_Number__c</fullName>
    <label>Billing Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <formula>Plant_Product__r.Plant__r.Name</formula>
    <label>Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the plant product you are relating the Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the plant product you are relating the Forecast Record to.</inlineHelpText>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NameMappingConfigurationTriggerTest.cls
@isTest(SeeAllData=false)
public class NameMappingConfigurationTriggerTest{
    
    static testMethod void unitTest01(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
        System.RunAs(u) {
            listAccount.add(new Account(Name = 'Test Account', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210', recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account5', Billing_Account_Number__c = '019.0922', recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account'));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Billing Account Number', SFDC_Value__c = '019.0922', Mapped_Value__c = '19.0922', Account__c = listAccount.get(4).Id));
        }
        
        test.startTest();
            insert listNMC;
            
            List<Name_Mapping_Configuration__c> nmcList = [Select Id, Account__c,User__c,Plant_Product__c,Message__c from Name_Mapping_Configuration__c where Id =: listNMC[0].Id];
            
            //system.assertEquals(null,nmcList[0].Account__c);
            //system.assertEquals(null,nmcList[0].User__c);
            //system.assertEquals(null,nmcList[0].Plant_Product__c);
            //system.assertEquals(System.label.No_Account_Match_Found,nmcList[0].Message__c);
            
        test.stopTest();
    }
    
    static testMethod void unitTest02(){ 
        User u = CreateUser();
        insert u;
    
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
        System.RunAs(u) {
            listAccount.add(new Account(Name = 'Test Account',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account5', Billing_Account_Number__c = '019.0922',recordTypeId = recordTypeId));
            insert listAccount;
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
            
            List<Account> accs = [Select id, Name from Account where Name =: 'Test Account'];
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Billing Account Number', SFDC_Value__c = '019.092255', Mapped_Value__c = '19.0922'));
        }
        
        test.startTest();
            insert listNMC;
            
            listNMC.get(0).SFDC_Value__c = 'Test Error record';
            listNMC.get(1).SFDC_Value__c = 'Test Error record';
            listNMC.get(2).SFDC_Value__c = 'Test Error record';
            update listNMC;
            
             List<Name_Mapping_Configuration__c> nmcList = [Select Id, Account__c,User__c,Plant_Product__c,Message__c from Name_Mapping_Configuration__c where Id =: listNMC[0].Id];
            
            //system.assertEquals(null,nmcList[0].Account__c);
            //system.assertEquals(null,nmcList[0].User__c);
            //system.assertEquals(null,nmcList[0].Plant_Product__c);
            
        test.stopTest();
    }
    
    static testMethod void unitTestUserActive(){ 
        User u = CreateUser();
        
       // u.IsActive = false;
        insert u;
        
   	 
        list<Account> listAccount = new list<Account>();
        list<Name_Mapping_Configuration__c> listNMC = new list<Name_Mapping_Configuration__c>();
        list<Sales_Data__c> listSD = new list<Sales_Data__c>();
        list<Raw_Sales_Data__c> listRSD = new list<Raw_Sales_Data__c>();
        list<Plant_Products__c> listPP = new list<Plant_Products__c>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
            listAccount.add(new Account(Name = 'Test Account',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account2',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account3',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account4', Billing_Account_Number__c = '9874563210',recordTypeId = recordTypeId));
            listAccount.add(new Account(Name = 'Test Account5', Billing_Account_Number__c = '019.0922',recordTypeId = recordTypeId));
        System.runAs(u){
            insert listAccount;
        }    
        
            
            Plant__c p = new Plant__c(Name = 'Test Plant name');
            insert p;
            listPP.add(new Plant_Products__c(Name = 'Test Plant name', Plant__c = p.id));
            insert listPP;
            
           
    		
            List<Account> accs = [Select id, Name from Account where Name =: 'Test Account'];
            
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Account Name', SFDC_Value__c = 'Test Account', Mapped_Value__c = 'Test Account', Account__c = listAccount.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'User Name', SFDC_Value__c = 'Testing User', Mapped_Value__c = 'Testing User', User__c = u.Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Plant Product Name', SFDC_Value__c = 'Test Plant name-', Mapped_Value__c = 'Test Plant name-', Plant_Product__c = listPP.get(0).Id ));
            listNMC.add(new Name_Mapping_Configuration__c(Billing_System__c = 'All', Type__c = 'Billing Account Number', SFDC_Value__c = '019.092255', Mapped_Value__c = '19.0922'));
        
        test.startTest();
        	
            insert listNMC;
            
            listNMC.get(0).SFDC_Value__c = 'Test Error record';
            listNMC.get(1).SFDC_Value__c = 'Test Error record';
            listNMC.get(2).SFDC_Value__c = 'Test Error record';
            update listNMC;
            
             List<Name_Mapping_Configuration__c> nmcList = [Select Id, Account__c,User__c,Plant_Product__c,Message__c from Name_Mapping_Configuration__c where Id =: listNMC[0].Id];
            
            //system.assertEquals(null,nmcList[0].Account__c);
            //system.assertEquals(null,nmcList[0].User__c);
            //system.assertEquals(null,nmcList[0].Plant_Product__c);
            
        test.stopTest();
    }
    
    public static User createUser() {
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(alias = 'tesusr', email = 'testinguser@newtest.com',
            emailencodingkey = 'UTF-8', lastname = 'Testing User', languagelocalekey = 'en_US',
            localesidkey = 'en_US', profileid = p.Id,
            timezonesidkey = 'America/Los_Angeles', username = 'testinguser@newtest.com',EmployeeNumber = '12321');
           
        return u;
    }
}