force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Forecast_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Amount__c</fullName>
    <description>Update the forecast dollar ($) amount.</description>
    <inlineHelpText>Update the forecast dollar ($) amount.</inlineHelpText>
    <label>Forecast Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the plant product you are relating the Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the plant product you are relating the Forecast Record to.</inlineHelpText>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesDataMergeSetting__c/SalesDataMergeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SalesDataMergeSetting</label>
</CustomObject>

force-app/main/default/classes/InvokeAccountSalesDataMerge.cls
public with sharing class InvokeAccountSalesDataMerge {
  public pagereference runBatch(){
  
    String strCurrYear = '';
   /* SalesDataMergeSetting__c sdm = SalesDataMergeSetting__c.getValues('SalesDataYear');
    if(sdm != null && sdm.Year__c != null)
        strCurrYear = sdm.Year__c; */
  
    //String strCurrYear = String.valueOf(Date.today().Year());
    System.debug('strCurrYear = ' + strCurrYear); 
    String str1 = '';
    if(strCurrYear == ''){
        str1 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c';
    }
    else{
        str1 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c WHERE Year__c = \'' + strCurrYear + '\'';
    }
    AccountSalesDataMerge uai1 = new AccountSalesDataMerge(str1);
    id batchstart1= Database.executeBatch(uai1, 10);
    return null;
  }
}