force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Forecast_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Amount__c</fullName>
    <description>Update the forecast dollar ($) amount.</description>
    <inlineHelpText>Update the forecast dollar ($) amount.</inlineHelpText>
    <label>Forecast Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Historical_Owner__c.field-meta.xml
<CustomField>
    <fullName>Historical_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used to keep track of owner of sales data.</description>
    <inlineHelpText>This field indicates historical owner of data and not the current owner of account.</inlineHelpText>
    <label>Historical Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Margin_Sales_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Margin_Sales_Dollars__c</fullName>
    <label>Margin Sales Dollars</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the plant product you are relating the Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the plant product you are relating the Forecast Record to.</inlineHelpText>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesDataMergeSetting__c/SalesDataMergeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SalesDataMergeSetting</label>
</CustomObject>

force-app/main/default/classes/TestAccountSalesDataMerge.cls
@isTest
private class TestAccountSalesDataMerge {
 public static User managerUser1;
    @testSetup 
    public static void setupmethod(){
	 Profile p = [select id from profile where name='System Administrator'];
        
     String name = 'A-test1';
     managerUser1 = new User(Alias = name, Email = name + '@asdfg.junk', EmailEncodingKey = 'UTF-8',
            FirstName = 'Test', lastname = name, LanguageLocaleKey = 'en_US', LocaleSIDKey = 'en_US',
            Profileid = p.Id, TimezoneSIDKey = 'America/Los_Angeles', Username = name + '@asdfg.junk',EmployeeNumber = '101');
        
        insert managerUser1;        
    }
    static testMethod void startTest(){
        User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
   //create Account
   
        Account acc = new Account();
        acc.Name='Test Acc';
        acc.Industry = 'Business Services';
        acc.Type = 'Customer';
        acc.RecordTypeId = recordTypeId;
        acc.OwnerId = managerUser.Id;
        insert acc;
        
        
        //create sales data
        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
        Sales_Data__c sd = new Sales_Data__c();
        sd.Year__c = '2014';
        sd.Period__c = 1;
        sd.Actual_Amount__c = 100;   
        sd.Account__c = acc.id; 
        sd.Margin_Sales_Dollars__c = 20;   
        sdlist.add(sd);

        sd = new Sales_Data__c();
        sd.Year__c = '2014';
        sd.Period__c = 1;
        sd.Actual_Amount__c = 100;   
        sd.Account__c = acc.id; 
        sd.Historical_Owner__c  = UserInfo.getUserId();  
        sdlist.add(sd);
        //
        insert sdlist;
        test.startTest();
        Set<Id> setAccountId = new Set<Id>();
        setAccountId.add(acc.Id);
        AccountSalesDataMerge.runAccountSalesDataMerge(setAccountId,'2015');
        //
        
        String str = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
       AccountSalesDataMerge rr = new AccountSalesDataMerge(str);
    id batchstart= Database.executeBatch(rr);
    
    AccountSalesDataMerge.runAccountSalesDataMerge(setAccountId,null);
    String str1 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
    AccountSalesDataMerge rr1 = new AccountSalesDataMerge(str1);
    id batchstart1= Database.executeBatch(rr1);
    
    Set<Id> setAccountsId = new Set<Id>();
    AccountSalesDataMerge.runAccountSalesDataMerge(setAccountsId,'2015');
    String str2 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
    AccountSalesDataMerge rr2 = new AccountSalesDataMerge(str2);
    id batchstart2= Database.executeBatch(rr2);
    
    //
    SalesDataMergeSetting__c customSales = new SalesDataMergeSetting__c(Name = 'SalesDataYear',Year__c = '2015');
    insert customSales;
    
     
     String jobId = System.schedule('testsch', ScheduleAccountSalesDataMerge.CRON_EXP, new ScheduleAccountSalesDataMerge());
       // Get the information from the CronTrigger API object
       CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
       // Verify the expressions are the same
       System.assertEquals(ScheduleAccountSalesDataMerge.CRON_EXP, ct.CronExpression);
       
       //
       InvokeAccountSalesDataMerge up = new InvokeAccountSalesDataMerge();
       up.runBatch();
       
       SalesDataMergeSetting__c customSalesDM = new SalesDataMergeSetting__c(Name = 'SalesDataYear',Year__c = '2015');
    	insert customSalesDM;
       InvokeAccountSalesDataMerge up1 = new InvokeAccountSalesDataMerge();
       up1.runBatch();
        test.stopTest();
	}
	
	//Test method for  test else cases
	static testMethod void startTest2(){
		User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
  		//create Account
        Account acc = new Account();
        acc.Name='Test Acc';
        acc.Industry = 'Business Services';
        acc.Type = 'Customer';
        acc.recordTypeId = recordTypeId;
        acc.OwnerId = managerUser.Id;
        insert acc;
        
        
        //create sales data
        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
        Sales_Data__c sd = new Sales_Data__c();
        sd.Year__c = '2014';
        sd.Period__c = 1;
        sd.Actual_Amount__c = 100;   
        sd.Account__c = acc.id; 
        sd.Margin_Sales_Dollars__c = 20;   
        sdlist.add(sd);

        sd = new Sales_Data__c();
        sd.Year__c = '2014';
        sd.Period__c = 1;
        sd.Actual_Amount__c = 100;   
        sd.Account__c = acc.id; 
        sd.Historical_Owner__c  = UserInfo.getUserId();  
        sdlist.add(sd);
        //
        insert sdlist;
        Test.startTest();
        Set<Id> setAccountId = new Set<Id>();
        setAccountId.add(acc.Id);
        AccountSalesDataMerge.runAccountSalesDataMerge(setAccountId,'2015');
        //
        
        String str = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
       AccountSalesDataMerge rr = new AccountSalesDataMerge(str);
    id batchstart= Database.executeBatch(rr);
    
    AccountSalesDataMerge.runAccountSalesDataMerge(setAccountId,null);
    String str1 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
    AccountSalesDataMerge rr1 = new AccountSalesDataMerge(str1);
    id batchstart1= Database.executeBatch(rr1);
    
    Set<Id> setAccountsId = new Set<Id>();
    AccountSalesDataMerge.runAccountSalesDataMerge(setAccountsId,'2015');
    String str2 = 'SELECT Id, Account__c, Account__r.Id, Plant_Product__c, Plant_Product__r.Id, Budget_Amount__c, Year__c, Period__c, Actual_Amount__c, Forecast_Amount__c FROM Sales_Data__c LIMIT 1';
    AccountSalesDataMerge rr2 = new AccountSalesDataMerge(str2);
    id batchstart2= Database.executeBatch(rr2);
    
    //
    SalesDataMergeSetting__c customSales = new SalesDataMergeSetting__c(Name = 'SalesDataYear');
    insert customSales;
    
     String jobId = System.schedule('testsch', ScheduleAccountSalesDataMerge.CRON_EXP, new ScheduleAccountSalesDataMerge());
       // Get the information from the CronTrigger API object
       CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
       // Verify the expressions are the same
       System.assertEquals(ScheduleAccountSalesDataMerge.CRON_EXP, ct.CronExpression);
       
       //
       InvokeAccountSalesDataMerge up = new InvokeAccountSalesDataMerge();
       up.runBatch();
       
       SalesDataMergeSetting__c customSalesDM = new SalesDataMergeSetting__c(Name = 'SalesDataYear');
    	insert customSalesDM;
       InvokeAccountSalesDataMerge up1 = new InvokeAccountSalesDataMerge();
       up1.runBatch();
        Test.stopTest();
 }
}