force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Products__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plant_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>(0)</defaultValue>
    <inlineHelpText>Starting in 2020, Actual Amount represents Shipped Sales. All other years represent Invoiced Sales.</inlineHelpText>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Actual_Units__c.field-meta.xml
<CustomField>
    <fullName>Actual_Units__c</fullName>
    <label>Actual Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <formula>Plant_Product__r.Plant__r.Name</formula>
    <label>Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the plant product you are relating the Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the plant product you are relating the Forecast Record to.</inlineHelpText>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Plant_Product__r.Product__r.Name</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Batch_SalesDataBlankUpdate.cls
@isTest
private class Test_Batch_SalesDataBlankUpdate {
	public static User managerUser1;
    @testSetup 
    public static void setupmethod(){
	 Profile p = [select id from profile where name='System Administrator'];
        
     String name = 'A-test1';
     managerUser1 = new User(Alias = name, Email = name + '@asdfg.junk', EmailEncodingKey = 'UTF-8',
            FirstName = 'Test', lastname = name, LanguageLocaleKey = 'en_US', LocaleSIDKey = 'en_US',
            Profileid = p.Id, TimezoneSIDKey = 'America/Los_Angeles', Username = name + '@asdfg.junk',EmployeeNumber = '101');
        
        insert managerUser1;        
    }
    static testMethod void myUnitTest() {
       User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
       //List Of Sales Data
       
	    //List of Accounts for customer
	   	List<Account> accounts = new List<Account>();
    		
		//Create Account and add to list
        for(Integer i = 0;i < 3; i++) {
          Account acc = new Account(Name='Test'+i+'Acc',Industry = 'Business Services',Type = 'Customer',recordTypeId = recordTypeId);
          accounts.add(acc);
        }
        
        //Insert Accounts
        System.runAs(managerUser){
            insert accounts;
        }
        
	       
        //Create Plant
        Plant__c plant =  new Plant__c(Name = 'TestPlant' ,City__c = 'Jaipur');
        insert plant;
	        
        //Create Product 
        Product2 prod = new Product2(Name = 'TestProduct');
        insert prod;
        
        //Create PlantProduct
        Plant_Products__c plantProd = new Plant_Products__c (Name = 'Test',Plant__c = plant.Id,Product__c = prod.Id);
        insert plantProd;
	    
	    
	        
	    //List of sales data
        List<Sales_Data__c> sdlist = new List<Sales_Data__c>();
	        
  		//List Of accounts
     	List<Account> accountList = [Select Id from Account Where Type = 'Customer'];
	      
      	//Assert  
        system.assertEquals(3,accountList.size());
        
        //Plant product
        Plant_Products__c plantproduct = [Select Id From Plant_Products__c Limit 1];
	        
        //Create Sales Data and add to list
        for(Integer i = 0; i < accountList.size(); i++) {
          
          Sales_Data__c sd = new Sales_Data__c();
          sd.Account__c = accountList[i].Id;
          sd.Plant_Product__c = plantproduct.Id;
          sd.Year__c = String.valueOf(Date.today().Year());
          sd.Period__c = 10;
          sd.Actual_Amount__c = 100;   
          sd.Actual_Units__c = 20;
          sdlist.add(sd);
        }
        insert sdlist;
        
       	//Test Start
        Test.startTest();
        
        List<Sales_Data__c> sdLists = [Select Id, Month__c from Sales_Data__c where Id IN: sdlist];
        sdLists[0].Month__c = '';
        sdLists[1].Month__c = '';
        update sdList;
        
        sdLists = [Select Id, Month__c from Sales_Data__c where Month__c = null];
        
        system.debug('@#@#@#'+sdLists);
        Batch_SalesDataBlankUpdate batch = new Batch_SalesDataBlankUpdate('LastModifiedDate desc');
        DataBase.executeBatch(batch);
        
        Test.stopTest();
    }
}