force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plant_Products__c/Plant_Products__c.object-meta.xml
<CustomObject>
    <label>Plant Product</label>
    <nameField>
        <label>Plant Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant_Products__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plant_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Products</relationshipLabel>
    <relationshipName>Plant_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/Sales_Data__c.object-meta.xml
<CustomObject>
    <label>Sales Data</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Sales Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the account you are adding a new Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the account you are adding a new Forecast Record to.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <description>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</description>
    <inlineHelpText>Period is used to identify the specific month the sale is coming out of. 

When forecasting, you will only have to add one period/month to the forecast line and the remaining periods will auto-populate for you. 
(ie - January = 1; August = 8)</inlineHelpText>
    <label>Period</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <formula>Plant_Product__r.Plant__r.Name</formula>
    <label>Plant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Use the lookup link to locate the plant product you are relating the Forecast Record to.</description>
    <inlineHelpText>Use the lookup link to locate the plant product you are relating the Forecast Record to.</inlineHelpText>
    <label>Plant Product</label>
    <referenceTo>Plant_Products__c</referenceTo>
    <relationshipLabel>Sales Data</relationshipLabel>
    <relationshipName>Sales_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Plant_Product__r.Product__r.Name</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>text(YEAR(today()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Data__c/recordTypes/Forecast_Sales_Data.recordType-meta.xml
<RecordType>
    <fullName>Forecast_Sales_Data</fullName>
    <active>true</active>
    <description>Used when creating forecasted Sales Data records from the Forecast VF page.</description>
    <label>Forecast Sales Data</label>
</RecordType>

force-app/main/default/classes/Test_AddSalesDataController.cls
@isTest
private class Test_AddSalesDataController {
	public static User managerUser1;
    @testSetup 
    public static void setupmethod(){
	 Profile p = [select id from profile where name='System Administrator'];
        
     String name = 'A-test1';
     managerUser1 = new User(Alias = name, Email = name + '@asdfg.junk', EmailEncodingKey = 'UTF-8',
            FirstName = 'Test', lastname = name, LanguageLocaleKey = 'en_US', LocaleSIDKey = 'en_US',
            Profileid = p.Id, TimezoneSIDKey = 'America/Los_Angeles', Username = name + '@asdfg.junk',EmployeeNumber = '101');
        
        insert managerUser1;        
    }
    
    static testMethod void myUnitTest() {
        User managerUser = [select id from User where Email = 'A-test1@asdfg.junk'];
		
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Cenveo').getRecordTypeId();
        //Record Type
        List<RecordType> rType = [Select Id From RecordType Where SObjectType = 'Sales_Data__c' AND DeveloperName = 'Forecast_Sales_Data' AND isActive=true LIMIT 1];
        List<Account> accList = new List<Account>();
        accList.add(new Account(Name = 'TestSales', Type = 'Customer', recordTypeId= recordTypeId));
        System.runAs(managerUser){
            insert accList;
        }
        
        
        //Create Plant
        Plant__c plant =  new Plant__c(Name = 'TestPlant' ,City__c = 'Jaipur');
        insert plant;
        
        //Create Product 
        Product2 prod = new Product2(Name = 'TestProduct');
        insert prod;
        
        //Create PlantProduct
        Plant_Products__c plantProd = new Plant_Products__c (Name = 'Test',Plant__c = plant.Id,Product__c = prod.Id);
        insert plantProd;
        
        //Set Account Id in page url
        ApexPages.CurrentPage().getParameters().put('accid',accList[0].Id);
        
        //Test start here
        Test.startTest();
        
        //Instance of standard controller
        ApexPages.StandardController stdCont = new ApexPages.StandardController(accList[0]);
        
        //Instance of  conroller class
        AddSalesDataController controller = new AddSalesDataController(stdCont);
        
        //Set properties  for controller 
        controller.sd.Account__c = accList[0].Id;
        controller.sd.Plant_Product__c = plantProd.Id;
        controller.sd.Year__c = String.valueOf(Date.today().Year());
        controller.sd.Period__c = 12;
        
        //Controller method call
        controller.doSave();
        
        //Query sales data record
        List<Sales_Data__c> sdList = [Select id, Account__c, Plant_Product__c, Year__c from Sales_Data__c where Account__c =: accList[0].Id AND Plant_Product__c =: plantProd.Id];
        
        //Asserts
        System.assert(sdList.size() > 0);
        System.assertEquals(false,controller.errorLog);
       	
       	//Set properties of controller
        controller.sd.Account__c = accList[0].Id;
        controller.sd.Plant_Product__c = plantProd.Id;
        controller.sd.Year__c = String.valueOf(Date.today().Year());
        controller.sd.Period__c = 12;
        
        //save method call
        controller.doSave();
       	
       	//Assert
       	System.assertEquals(true,controller.errorLog);
        
        //Reintialize controller instance
        controller = new AddSalesDataController(stdCont);
        controller.sd.Period__c = 11;
        controller.doSave();
        
        //Query sales data record
        sdList = [Select id, Account__c, Plant_Product__c, Year__c from Sales_Data__c where Period__c =11];
        
        //Asserts
        System.assertEquals(0,sdList.size());
        System.assertEquals(true,controller.errorLog);
        
        //Reintialize controller instance
        controller = new AddSalesDataController(stdCont);
        controller.sd.Year__c = '2015';
        controller.doSave();
        
        //Query sales data record
        sdList = [Select id, Account__c, Plant_Product__c, Year__c from Sales_Data__c where Year__c = '2015'];
        
        //Assert
        System.assertEquals(0,sdList.size());
        
        //Reintialize controller instance
        controller = new AddSalesDataController(stdCont);
        controller.sd.Year__c = '2015';
        controller.sd.Period__c = 13;
        controller.doSave();
        
        //Query sales data record
        sdList = [Select id, Account__c, Plant_Product__c, Year__c from Sales_Data__c where Year__c = '2015' AND Period__c = 13];
        
        //Asserts
        System.assertEquals(0,sdList.size());
        System.assertEquals(true,controller.errorLog);
        
        //Reintialize controller instance
        controller = new AddSalesDataController(stdCont);
        controller.sd.Year__c = '2040';
        controller.sd.Period__c = 2;
        controller.doSave();
        
        //Query sales data record
        sdList = [Select id, Account__c, Plant_Product__c, Year__c from Sales_Data__c where Year__c ='2040'];
        
        //Asserts
        System.assertEquals(0,sdList.size());
        System.assertEquals(true,controller.errorLog);
        
        //Reintialize controller instance
        controller = new AddSalesDataController(stdCont);
        controller.sd.Year__c = '2022';
        controller.doCancel();
       
        //Test stop here
        Test.stopTest();
    }
}